// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ6HIsbPCj1XFOocuHOHyQvjBcDKxhkLE',
    appId: '1:12737610297:web:ef810f6a7da91f320843e8',
    messagingSenderId: '12737610297',
    projectId: 'todo-720f7',
    authDomain: 'todo-720f7.firebaseapp.com',
    storageBucket: 'todo-720f7.appspot.com',
    measurementId: 'G-ZDQQ1C6PTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijqhHu5Ej5Dy7YC1SxgHPsySUdMDoFMQ',
    appId: '1:12737610297:android:7fdb60a3f4007c7e0843e8',
    messagingSenderId: '12737610297',
    projectId: 'todo-720f7',
    storageBucket: 'todo-720f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtwumaMVhQHHVPflSqSu4H2b0EWKhDd4',
    appId: '1:12737610297:ios:ab1419f2eab29e000843e8',
    messagingSenderId: '12737610297',
    projectId: 'todo-720f7',
    storageBucket: 'todo-720f7.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRtwumaMVhQHHVPflSqSu4H2b0EWKhDd4',
    appId: '1:12737610297:ios:05ca60009108c1410843e8',
    messagingSenderId: '12737610297',
    projectId: 'todo-720f7',
    storageBucket: 'todo-720f7.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
